### ISSUE TITLE
业务请求正常，日志异步报错

### ISSUE THREAD

**Issue by heroman120** [minbox-projects/api-boot-admin#4]
![image](https://user-images.githubusercontent.com/30167005/97250364-c1016600-1840-11eb-8d48-b31a22349868.png)

**Comment by heroman120** [comment]
java.lang.NoClassDefFoundError: org/minbox/framework/util/JsonUtil
	at org.minbox.framework.logging.client.notice.support.LoggingLocalNotice.notice(LoggingLocalNotice.java:44) ~[minbox-logging-client-1.0.5.RELEASE.jar:na]
	at org.minbox.framework.logging.client.notice.LoggingNoticeListener.lambda$onApplicationEvent$0(LoggingNoticeListener.java:73) ~[minbox-logging-client-1.0.5.RELEASE.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_152]
	at org.minbox.framework.logging.client.notice.LoggingNoticeListener.onApplicationEvent(LoggingNoticeListener.java:73) ~[minbox-logging-client-1.0.5.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: org.minbox.framework.util.JsonUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	... 17 common frames omitted

**Comment by hengboy** [comment]
因为minbox-logging内部所依赖的minbox-core内JSON格式化工具类版本不兼容问题导致。

修改方式如下：

**1. admin-service项目pom.xml：**
```
<!--ApiBoot Logging-->
<!-- 分布式日志文档：http://apiboot.minbox.io/zh-cn/docs/api-boot-logging.html -->
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>api-boot-starter-logging</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-spring-context</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-client</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-spring-context</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>
```
> 替换原`api-boot-starter-logging`依赖为上面内容。

**2. admin-log-server项目pom.xml：**
```
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>api-boot-starter-logging-admin</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-client</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.minbox.framework</groupId>
            <artifactId>minbox-logging-spring-context</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-admin</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.minbox.framework</groupId>
    <artifactId>minbox-logging-spring-context</artifactId>
    <version>1.0.6-SNAPSHOT</version>
</dependency>
```
> 替换原`api-boot-starter-logging-admin`依赖为上面内容。
